#!/bin/bash
f=TransferOfStatusReport.tex
g=TransferOfStatusReport.aux
if pdflatex $f
then
  cd fgraph
  MPFILES=`ls *.mp`
  for MP in ${MPFILES}; do
    mpost ${MP}
  done
  cd ..
  bibtex $g
  pdflatex $f
fi
